apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: CLO835
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
